name: Publish package to the Maven Central Repository
on:
  push:
    tags:
      - v*
  pull_request:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Create settings xml maven
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: '[{ "id":"ossrh", "username":"${{ secrets.JRELEASER_NEXUS2_USERNAME }}", "password":"${{ secrets.JRELEASER_NEXUS2_PASSWORD }}" }]'
          profiles: '[{"id":"ossrh","name":"ossrh","properties":{"gpg.executable":"gpg","gpg.passphrase":"${{ secrets.GPG_SIGN_PASS }}"}}]'
          active_profiles: '["ossrh"]'
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY_ARMOR }}
          passphrase: ${{ secrets.GPG_SIGN_PASS }}
      - name: List keys
        run: gpg -K
      - name: Publish package
        run: ./mvnw -Prelease deploy